import ts from '../frontend/node_modules/typescript/lib/typescript.js'
import fs from 'node:fs'
import path from 'node:path'
const packages=['design-components','kit-dashboard','kit-chat','design-bindings','kit-admin','kit-settings','kit-observe','kit-account','kit-code','kit-workflow','kit-voice']
const imports=new Map()
function scan(directory){for(const item of fs.readdirSync(directory,{withFileTypes:true})){const file=path.join(directory,item.name);if(item.isDirectory())scan(file);else if(/\.tsx?$/.test(file)){const source=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true);for(const statement of source.statements){if(!ts.isImportDeclaration(statement)||!ts.isStringLiteral(statement.moduleSpecifier))continue;const specifier=statement.moduleSpecifier.text;if(!specifier.startsWith('@hollis-labs/'))continue;const names=statement.importClause?.namedBindings;if(names&&ts.isNamedImports(names)){for(const name of names.elements){const key=specifier+'#'+(name.propertyName?.text??name.name.text),files=imports.get(key)??[];files.push(file);imports.set(key,files)}}}}}}
scan('frontend/src')
const inventory=[]
for(const name of packages){const root=path.resolve('frontend/node_modules/@hollis-labs/'+name),pkg=JSON.parse(fs.readFileSync(root+'/package.json'));for(const [sub,entry]of Object.entries(pkg.exports)){if(typeof entry!=='object'||!entry.types)continue;const file=path.resolve(root,entry.types),program=ts.createProgram([file],{noEmit:true,allowImportingTsExtensions:true,skipLibCheck:true,moduleResolution:ts.ModuleResolutionKind.Bundler,module:ts.ModuleKind.ESNext}),checker=program.getTypeChecker(),source=program.getSourceFile(file),symbol=checker.getSymbolAtLocation(source),specifier=pkg.name+(sub==='.'?'':sub.slice(1));for(const exported of checker.getExportsOfModule(symbol)){const target=exported.flags&ts.SymbolFlags.Alias?checker.getAliasedSymbol(exported):exported,value=!!(target.flags&ts.SymbolFlags.Value),sources=[...new Set(imports.get(specifier+'#'+exported.name)??[])];inventory.push({package:pkg.name,version:pkg.version,entry:sub,name:exported.name,category:value?'runtime-export':'type-export',coverage:sources.length?(value?'controlled composition import':'typed adapter import'):'unreviewed',sources});}}}
fs.writeFileSync('docs/export-inventory.json',JSON.stringify(inventory,null,2)+'\n')
console.log(`${inventory.length} declaration export names across ${packages.length} adopted packages; ${inventory.filter(x=>x.sources.length).length} exact public-entry imports. Import evidence is not exhaustive behavior coverage.`)
