import ts from '../frontend/node_modules/typescript/lib/typescript.js'
import fs from 'node:fs'
import path from 'node:path'
const packages=['design-components','kit-dashboard','kit-chat','design-bindings','kit-admin','kit-settings','kit-observe','kit-account','kit-code','kit-workflow','kit-voice','plugin-host-ui','design-app-runtime']
const policy=JSON.parse(fs.readFileSync('docs/coverage-policy.json','utf8'))
function reactRenderable(type) {
  if(type.isUnion())return type.types.some(reactRenderable)
  const symbol=type.getSymbol(), name=symbol?.getName(), declarations=symbol?.declarations??[]
  return ['Element','ReactElement','ReactNode','ReactPortal'].includes(name)&&declarations.some(d=>d.getSourceFile().fileName.includes('/@types/react/'))
}
const imports=new Map()
function scan(directory){for(const item of fs.readdirSync(directory,{withFileTypes:true})){const file=path.join(directory,item.name);if(item.isDirectory())scan(file);else if(/\.tsx?$/.test(file)){const source=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true);for(const statement of source.statements){if(!ts.isImportDeclaration(statement)||!ts.isStringLiteral(statement.moduleSpecifier))continue;const specifier=statement.moduleSpecifier.text;if(!specifier.startsWith('@hollis-labs/'))continue;const names=statement.importClause?.namedBindings;if(names&&ts.isNamedImports(names)){for(const name of names.elements){const key=specifier+'#'+(name.propertyName?.text??name.name.text),files=imports.get(key)??[];files.push(file);imports.set(key,files)}}}}}}
scan('frontend/src')
const inventory=[]
for(const name of packages){const root=path.resolve('frontend/node_modules/@hollis-labs/'+name),pkg=JSON.parse(fs.readFileSync(root+'/package.json'));for(const [sub,entry]of Object.entries(pkg.exports)){if(typeof entry!=='object'||!entry.types)continue;const file=path.resolve(root,entry.types),program=ts.createProgram([file],{noEmit:true,allowImportingTsExtensions:true,skipLibCheck:true,moduleResolution:ts.ModuleResolutionKind.Bundler,module:ts.ModuleKind.ESNext}),checker=program.getTypeChecker(),source=program.getSourceFile(file),symbol=checker.getSymbolAtLocation(source),specifier=pkg.name+(sub==='.'?'':sub.slice(1));for(const exported of checker.getExportsOfModule(symbol)){const target=exported.flags&ts.SymbolFlags.Alias?checker.getAliasedSymbol(exported):exported,value=!!(target.flags&ts.SymbolFlags.Value),sources=[...new Set(imports.get(specifier+'#'+exported.name)??[])],decl=target.valueDeclaration??target.declarations?.[0],type=decl&&checker.getTypeOfSymbolAtLocation(target,decl),signatures=type?.getCallSignatures()??[],returnTypes=signatures.map(s=>checker.typeToString(checker.getReturnTypeOfSignature(s))),description=type?checker.typeToString(type):'',visual=value&&/^[A-Z]/.test(exported.name)&&!/^use[A-Z]/.test(exported.name)&&(/ForwardRefExoticComponent|MemoExoticComponent/.test(description)||signatures.some(s=>reactRenderable(checker.getReturnTypeOfSignature(s)))),category=!value?'type-export':visual?'visual-component':signatures.length?'nonvisual-function':'runtime-value';
const rule=policy.exceptions.find(r=>r.package===pkg.name&&r.names.includes(exported.name)&&(!r.entries||r.entries.includes(sub))),family=policy.families.find(r=>r.package===pkg.name),disposition=rule?.disposition??(sources.length?'partial':'deferred'),evidence=rule?.evidence??(sources.length?family?.evidence??{}:{}),reason=rule?.reason??(sources.length?'Exact public-entry import and representative family evidence; independent export/state acceptance is incomplete.':'Public export tracked; no direct adoption or independent behavior proof.'),nextAction=rule?.nextAction??(sources.length?'Review this export against its own supported states and interactions before marking reviewed.':category==='visual-component'?'Inspect public props/CSS and add a bounded controlled story and keyboard/state check if this component is adopted.':category==='type-export'?'Review its public type contract with an appropriate positive/negative consumer assertion when adopted.':'Review deterministic utility/runtime contracts with focused nonvisual checks when adopted.');inventory.push({package:pkg.name,version:pkg.version,entry:sub,name:exported.name,category,classification:'React declaration symbol identity/call return/forward-ref analysis; uppercase callable names are visual; use* nonvisual',disposition,reason,nextAction,evidence,importEvidence:sources});}}}
const output=JSON.stringify(inventory,null,2)+'\n'
if(process.argv.includes('--check')){if(fs.readFileSync('docs/export-inventory.json','utf8')!==output)throw Error('Export inventory stale; run node scripts/coverage.mjs')}else fs.writeFileSync('docs/export-inventory.json',output)
for(const row of inventory){for(const key of ['pages','stories','checks'])for(const pointer of row.evidence[key]??[]){const [file,fragment]=pointer.split('#');if(!fs.existsSync(file))throw Error('Missing evidence '+pointer);if(fragment&&!fs.readFileSync(file,'utf8').includes(fragment))throw Error('Missing evidence anchor '+pointer)}}
const index=JSON.parse(fs.readFileSync('.scratch/storybook/index.json','utf8')).entries
for(const rule of [...policy.families,...policy.exceptions])for(const id of rule.evidence?.storyIds??[])if(index[id]?.type!=='story')throw Error('Missing story ID '+id)
for(const rule of policy.exceptions)for(const name of rule.names)if(!inventory.some(row=>row.package===rule.package&&row.name===name&&(!rule.entries||rule.entries.includes(row.entry))))throw Error('Unknown disposition export '+rule.package+'#'+name)
const counts={};for(const row of inventory)counts[row.disposition]=(counts[row.disposition]??0)+1
console.log(JSON.stringify({exports:inventory.length,packages:packages.length,categories:Object.fromEntries([...new Set(inventory.map(r=>r.category))].map(c=>[c,inventory.filter(r=>r.category===c).length])),dispositions:counts,exactImports:inventory.filter(r=>r.importEvidence.length).length})+'; disposition is tracking, not exhaustive behavior coverage.')

for(const [pkg,name,expected] of [['kit-dashboard','Panel','visual-component'],['kit-dashboard','ActivityHeatmap','visual-component'],['kit-dashboard','HourlyPulse','visual-component'],['design-components','Button','visual-component'],['design-components','cn','nonvisual-function'],['kit-dashboard','TimestampSampleChartProps','type-export']]) {
 const rows=inventory.filter(r=>r.package==='@hollis-labs/'+pkg&&r.name===name)
 if(!rows.length||rows.some(r=>r.category!==expected))throw Error('Classification regression '+pkg+'#'+name)
}
const catalogue=JSON.parse(fs.readFileSync('docs/design-kit-catalogue.json','utf8'))
for(const item of catalogue.catalogue){const pkg=JSON.parse(fs.readFileSync('frontend/node_modules/'+item.package+'/package.json'));if(pkg.name!==item.package)throw Error('Catalogue installation mismatch');if(item.package.includes('/kit-')&&!packages.includes(item.package.split('/')[1]))throw Error('Untracked kit catalogue package')}
const sourceArgument=process.argv.indexOf('--source-root')
const sourceRoot=sourceArgument>=0?path.resolve(process.argv[sourceArgument+1]):path.resolve('../../libs/design-kit')
if(process.argv.includes('--audit-source')) {
 const dirs=fs.readdirSync(sourceRoot+'/packages').filter(name=>fs.existsSync(sourceRoot+'/packages/'+name+'/package.json'))
 const actual=dirs.map(name=>JSON.parse(fs.readFileSync(sourceRoot+'/packages/'+name+'/package.json')).name).sort()
 if(JSON.stringify(actual)!==JSON.stringify(catalogue.catalogue.map(p=>p.package).sort()))throw Error('Read-only source catalogue drift')
 for(const item of catalogue.catalogue){const actual=JSON.parse(fs.readFileSync(sourceRoot+'/'+item.sourcePath));if(actual.version!==item.sourceVersion||actual.license!==item.license||!!actual.private!==item.private)throw Error('Read-only source metadata drift '+item.package)}
}
