// Explicit fictional board annotations keyed to immutable supplied task IDs.
// Canonical task-board statuses are authored; original graph task/run status remains in detail.
export const operationsMetadata: Record<
  string,
  {
    status: string
    priority: number
    manual: boolean
    system: boolean
    project: string
    epic: string
    sprint: string
    tag: string
    executor: string
  }
> = {
  "TASK-001": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-002": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-003": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-004": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-005": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-006": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-007": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-008": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-009": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-010": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-011": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-012": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-013": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-014": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-015": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-016": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-017": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: true,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-018": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-019": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-020": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-021": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-022": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-023": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-024": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-025": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-026": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-027": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-028": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-029": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-030": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-031": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-032": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-033": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-034": {
    status: "done",
    priority: 1,
    manual: false,
    system: true,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-035": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-036": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-037": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-038": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-039": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-040": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-041": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-042": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-043": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-044": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-045": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-046": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-047": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-048": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-049": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-050": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-051": {
    status: "review",
    priority: 3,
    manual: false,
    system: true,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-052": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-053": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-054": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-055": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-056": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-057": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-058": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-059": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-060": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-061": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-062": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-063": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-064": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-065": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-066": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-067": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-068": {
    status: "done",
    priority: 2,
    manual: false,
    system: true,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-069": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-070": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-071": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-072": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-073": {
    status: "doing",
    priority: 1,
    manual: true,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-074": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-075": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-076": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-077": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-078": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-079": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-080": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-081": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-082": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-083": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-084": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
  "TASK-085": {
    status: "doing",
    priority: 1,
    manual: true,
    system: true,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "codex",
  },
  "TASK-086": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "claude",
  },
  "TASK-087": {
    status: "review",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "cli",
  },
  "TASK-088": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "codex",
  },
  "TASK-089": {
    status: "blocked",
    priority: 2,
    manual: true,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "claude",
  },
  "TASK-090": {
    status: "todo",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "cli",
  },
  "TASK-091": {
    status: "backlog",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "codex",
  },
  "TASK-092": {
    status: "done",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "claude",
  },
  "TASK-093": {
    status: "paused",
    priority: 3,
    manual: true,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 1",
    tag: "security",
    executor: "cli",
  },
  "TASK-094": {
    status: "done",
    priority: 1,
    manual: false,
    system: false,
    project: "Gateway",
    epic: "Permission boundaries",
    sprint: "Review sprint 2",
    tag: "fixtures",
    executor: "codex",
  },
  "TASK-095": {
    status: "queued",
    priority: 2,
    manual: false,
    system: false,
    project: "Evidence pipeline",
    epic: "Receipt integrity",
    sprint: "Review sprint 1",
    tag: "observability",
    executor: "claude",
  },
  "TASK-096": {
    status: "done",
    priority: 3,
    manual: false,
    system: false,
    project: "Client workspace",
    epic: "Review experience",
    sprint: "Review sprint 2",
    tag: "interface",
    executor: "cli",
  },
}
