import fixtures from './fixture-operands.json'
const sessions = fixtures.sessions.map(x=>x.session)
const settings={default_provider:'fixture',default_model:'fictional-model',default_agent:'fixture-agent',utility_provider:'',utility_model:'',developer_mode:true,recover_mode:false,tool_call_display_mode:'minimal',tool_stream_behavior:'auto',tool_drawer_retention:60,provider_fallback_chain:[],embedding_provider:'',embedding_model:'',embedding_mode:'disabled',ext_settings:{display_name:'Fixture reviewer',active_theme:'nanite-default',theme_preference:'dark'}}
const empty = ['listProjects','listAgents','listSessionAgents','listTools','listToolServers','listPlugins','listPluginSlots','listPluginPanels','listPluginKeybindings','listUIComponents','listBookmarks','listDrawerCards','listPinnedContent','listDocuments','listTodos','listPlans','listReminders','listWorkers','listWorkflowRuns','listArtifacts','listAgentMessages','listAgentSkills','listAgentsStatus','listModels','listProviders','listCommands','listPluginCommands']
const values:any={getSettings:()=>settings,listSessions:()=>sessions,getSession:(id:string)=>({...sessions.find(s=>s.id===id),messages:fixtures.messages}),getMessagePage:()=>({messages:fixtures.messages,total:fixtures.messages.length,has_more:false}),getMessages:()=>fixtures.messages,fetchPluginRegistry:()=>({envelopes:{},widgets:{},slots:{},plugins:{}}),getSessionUsage:()=>({input_tokens:5000,output_tokens:3000,total_tokens:8000,tool_input_tokens:1000,estimated_cost_usd:0,message_count:3,cache_creation_tokens:0,cache_read_tokens:0}),getUsageSummary:()=>({total_tokens:8000,total_cost:0}),getContextBreakdown:()=>({total:8000,ceiling:32000,system_prompt_tokens:2000,tool_tokens_total:1000,tools_available:1,estimated_cost_usd:0,system_prompt_preview:'Fictional system prompt',message_tokens_total:5000,tools:[],messages:[],sections:[],skills:[],memories:[]}),getPermissionMode:()=>({mode:'ask'}),getShellMode:()=>({mode:'off'}),getShellInfo:()=>({work_dir:'fixture://empty-data'}),getScratchpad:()=>({content:'Fictional scratchpad.'}),getAgentState:()=>({}),getExecutionMetrics:()=>[],listUIComponents:()=>['session-info','context-budget','token-usage','tools'].map(id=>({id,type:'widget',name:id,description:'Fictional widget data'})),listProjects:()=>[{id:'fixture-project',name:'Fictional project',description:'No customer data',repo_path:'fixture://empty-data',settings:'{}',sort_order:0,created_at:fixtures.reference_time,updated_at:fixtures.reference_time}]}
Object.assign(values,{listUISlots:()=>({}),fetchTools:()=>[{name:'fixture_read',description:'Inert fixture only',input_schema:{type:'object'}}],fetchToolServers:()=>[{name:'fixture-server',tool_count:1,connected:false}],getSessionPluginEnvelopes:()=>[],getMessagingInbox:()=>[],getRecentExecutions:()=>[],listArtifactsByProject:()=>[]});
for(const name of empty)if(!values[name])values[name]=()=>[]
;(window as any).__fixtureAudit={calls:[],unavailable:[],writes:[],eventSources:[],intervals:[]}
export const api=new Proxy({}, {get(_target,name:string){return async(...args:any[])=>{const audit=(window as any).__fixtureAudit; audit.calls.push({name,args});if(/^(create|update|delete|set|respond|send|execute|pin|unpin|toggle|start|stop|cancel|grant|revoke|refresh|run|approve|reject|reload)/.test(name)){audit.writes.push(name);throw new Error('READONLY FIXTURE: '+name)}if(!values[name]){audit.unavailable.push(name);throw new Error('UNAVAILABLE FIXTURE: '+name)}return structuredClone(values[name](...args))}}}) as any
export class DrawerPinCapError extends Error {}
